### ISSUE TITLE
Spellcheck is on for password length <input> tag

### ISSUE THREAD

**Issue by Antosser** [AureumApes/SimplePasswordGenerator#2]
Add `spellcheck="false"` attribute to that <input> element, so it doesn't get checked for spelling by some software
![image](https://user-images.githubusercontent.com/71790328/214341202-895852f1-bb38-4ed9-95d9-f6b2d45292e8.png)

**Comment by AureumApes** [comment]
If you got Code suggestions please open a PR next time :)

**Comment by Antosser** [comment]
PRs require all that extra effort of forking & figuring out how to do all that. Would be much easier to just make the change on your side
