### ISSUE TITLE
"Probability" is unclear

### ISSUE THREAD

**Issue by Antosser** [AureumApes/SimplePasswordGenerator#3]
![image](https://user-images.githubusercontent.com/71790328/214341425-ccd5c9f2-3c7f-4e6e-b802-b3df5d62a4d1.png)
It just says `Probability` when it's not.  
You could however ...
* Replace `Probability` with `Inverse probability of guessing in one try`
* Replace `Probability` with `Maximum attempts needed to guess the password`

**Comment by AureumApes** [comment]
Thx, will fix this
